#the docker compose file version
version: "3.7"
services:
  client:
    container_name: mbb-client
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=mbb-staging.metasora.com
      - LETSENCRYPT_HOST=mbb-staging.metasora.com
      - LETSENCRYPT_EMAIL=metasoradev@gmail.com
  server:
    container_name: mbb-server
    build:
      context: .
      dockerfile: Dockerfile-server
    environment:
      - VIRTUAL_HOST=mbb-app-staging.metasora.com
      - LETSENCRYPT_HOST=mbb-app-staging.metasora.com
      - LETSENCRYPT_EMAIL=metasoradev@gmail.com

networks:
  default:
    external:
      name: webproxy
