#the docker compose file version
version: "3.7"
services:
  client:
    container_name: mbb-client
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "80:80"
    environment:
      - NODE_ENV=staging
      - VIRTUAL_HOST=mail-my-ballot.metasora.com
      - LETSENCRYPT_HOST=mail-my-ballot.metasora.com
      - LETSENCRYPT_EMAIL=metasoradev@gmail.com

networks:
  default:
    external:
      name: webproxy
