import { States } from "./states"

type Status = "Excuse" | "NoExcuse" | "Automatic" | "Website" | "VbmApp"

export const vbmStatus = (state: States): Status => {
  switch (state) {
    case "Alabama": return "Excuse"
    case "Alaska": return "NoExcuse"
    case "Arizona": return "NoExcuse"
    case "Arkansas": return "Excuse"
    case "California": return "NoExcuse"
    case "Colorado": return "Automatic"
    case "Connecticut": return "Excuse"
    case "Delaware": return "Excuse"
    case "District of Columbia": return "NoExcuse"
    case "Florida": return "VbmApp"
    case "Georgia": return "NoExcuse"
    case "Hawaii": return "NoExcuse"
    case "Idaho": return "NoExcuse"
    case "Illinois": return "NoExcuse"
    case "Indiana": return "Excuse"
    case "Iowa": return "NoExcuse"
    case "Kansas": return "NoExcuse"
    case "Kentucky": return "Excuse"
    case "Louisiana": return "Excuse"
    case "Maine": return "NoExcuse"
    case "Maryland": return "NoExcuse"
    case "Massachusetts": return "Excuse"
    case "Michigan": return "NoExcuse"
    case "Minnesota": return "NoExcuse"
    case "Mississippi": return "Excuse"
    case "Missouri": return "Excuse"
    case "Montana": return "NoExcuse"
    case "Nebraska": return "NoExcuse"
    case "Nevada": return "NoExcuse"
    case "New Hampshire": return "Excuse"
    case "New Jersey": return "NoExcuse"
    case "New Mexico": return "NoExcuse"
    case "New York": return "Excuse"
    case "North Carolina": return "NoExcuse"
    case "North Dakota": return "NoExcuse"
    case "Ohio": return "NoExcuse"
    case "Oklahoma": return "NoExcuse"
    case "Oregon": return "Automatic"
    case "Pennsylvania": return "Excuse"
    case "Rhode Island": return "NoExcuse"
    case "South Carolina": return "Excuse"
    case "South Dakota": return "NoExcuse"
    case "Tennessee": return "Excuse"
    case "Texas": return "Excuse"
    case "Utah": return "Automatic"
    case "Vermont": return "NoExcuse"
    case "Virginia": return "Excuse"
    case "Washington": return "Automatic"
    case "West Virginia": return "Excuse"
    case "Wisconsin": return "NoExcuse"
    case "Wyoming": return "NoExcuse"
  }
}
